### ISSUE TITLE
Allow usage of eslint 5

### ISSUE THREAD

**Issue by flootr** [Automattic/eslint-config-wpcalypso#21]
[For Calypso we'd like to update eslint to version 5](https://github.com/Automattic/wp-calypso/pull/25806). We get a npm dependency warning for this package though as this package requires either eslint `^3.3.1` or `^4.6.1`:

```
npm WARN eslint-config-wpcalypso@4.0.0 requires a peer of eslint@^3.3.1 || ^4.6.1 but none is installed. You must install peer dependencies yourself.
```

Are there any reasons why we shouldn't support v5 as well?

**Comment by aduth** [comment]
>Are there any reasons why we shouldn't support v5 as well?

Nope, no reason 😄
